// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.2
// source: pak.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pkg1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	String_ *String1 `protobuf:"bytes,1,opt,name=String,proto3" json:"String,omitempty"`
}

func (x *Pkg1) Reset() {
	*x = Pkg1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pak_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pkg1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pkg1) ProtoMessage() {}

func (x *Pkg1) ProtoReflect() protoreflect.Message {
	mi := &file_pak_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pkg1.ProtoReflect.Descriptor instead.
func (*Pkg1) Descriptor() ([]byte, []int) {
	return file_pak_proto_rawDescGZIP(), []int{0}
}

func (x *Pkg1) GetString_() *String1 {
	if x != nil {
		return x.String_
	}
	return nil
}

var File_pak_proto protoreflect.FileDescriptor

var file_pak_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x61, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x6b, 0x67,
	0x1a, 0x0b, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a,
	0x04, 0x50, 0x6b, 0x67, 0x31, 0x12, 0x26, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x31, 0x52, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x42, 0x2b, 0x5a,
	0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x75, 0x6e, 0x6d,
	0x61, 0x6f, 0x2d, 0x4a, 0x61, 0x7a, 0x7a, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x64, 0x65, 0x6d,
	0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pak_proto_rawDescOnce sync.Once
	file_pak_proto_rawDescData = file_pak_proto_rawDesc
)

func file_pak_proto_rawDescGZIP() []byte {
	file_pak_proto_rawDescOnce.Do(func() {
		file_pak_proto_rawDescData = protoimpl.X.CompressGZIP(file_pak_proto_rawDescData)
	})
	return file_pak_proto_rawDescData
}

var file_pak_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pak_proto_goTypes = []interface{}{
	(*Pkg1)(nil),    // 0: pkg.Pkg1
	(*String1)(nil), // 1: hello.String1
}
var file_pak_proto_depIdxs = []int32{
	1, // 0: pkg.Pkg1.String:type_name -> hello.String1
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pak_proto_init() }
func file_pak_proto_init() {
	if File_pak_proto != nil {
		return
	}
	file_hello_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pak_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pkg1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pak_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pak_proto_goTypes,
		DependencyIndexes: file_pak_proto_depIdxs,
		MessageInfos:      file_pak_proto_msgTypes,
	}.Build()
	File_pak_proto = out.File
	file_pak_proto_rawDesc = nil
	file_pak_proto_goTypes = nil
	file_pak_proto_depIdxs = nil
}
